---

kind: Service
apiVersion: v1
metadata:
  name: kong
spec:
  ports:
    - name: https
      port: 8443
      nodePort: 0
      protocol: TCP
    - name: http
      port: 8000
      nodePort: 0
      protocol: TCP
    - name: admin
      port: 8001
      nodePort: 0
      protocol: TCP
  type: NodePort
  selector:
    app: kong

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kong
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: "mashape/kong"
          env:
            - name: DATABASE
              value: cassandra
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 7946