---

kind: Service
apiVersion: v1
metadata:
  name: kong-database
spec:
  ports:
    - name: cassandra
      port: 9042
      nodePort: 0
      protocol: TCP
  type: ClusterIP
  selector:
    app: kong-database

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kong-database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kong-database
    spec:
      containers:
        - name: kong-database
          image: "cassandra:2.2"
          ports:
            - containerPort: 9042